# Generated by Django 5.1.6 on 2025-02-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='perm',
            new_name='acting',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='temp',
            new_name='permanent',
        ),
        migrations.AddField(
            model_name='staff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='temporary',
            field=models.BooleanField(default=False),
        ),
    ]
