# Generated by Django 5.1.6 on 2025-02-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_rename_perm_staff_acting_rename_temp_staff_permanent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='small_role_as',
            new_name='same_role_as',
        ),
    ]
