# Generated by Django 5.1.6 on 2025-02-26 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_status_alter_staff_options_alter_staff_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='acting',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='permanent',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='temporary',
        ),
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='staff.status'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
