# Generated by Django 5.1.6 on 2025-02-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_status_options_remove_staff_acting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='phone',
        ),
        migrations.AddField(
            model_name='staff',
            name='key_access_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='other',
            field=models.TextField(blank=True, null=True),
        ),
    ]
